//===- FinalImageObjectWriter.cpp - Object writer for rewriting -----------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
///
/// \file
/// FinalImageObjectWriter walks MCAssembler sections after all fixups have been
/// resolved by AddressModelBackend, copies fragment contents at their final VAs,
/// collects symbol addresses, and runs the ImagePostProcess hook.
/// recordRelocation unconditionally suppresses — any fixup reaching it has
/// already been back-filled by AddressModelBackend + stock applyFixup.
///
//===----------------------------------------------------------------------===//

#include "FinalImageObjectWriter.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/raw_ostream.h"

using namespace llvm;

void FinalImageObjectWriter::recordRelocation(const MCFragment &F,
                                              const MCFixup &Fixup,
                                              MCValue Target,
                                              uint64_t &FixedValue) {
  // AddressModelBackend::evaluateFixup has already resolved the value and the
  // bytes have been back-filled. shouldForceRelocation in the target backend
  // (e.g. AArch64 forces ADRP) may still route through here — suppress those
  // false positives: if the symbol is defined / in-section / absolute, or if
  // the caller's resolve callback can handle it, it is not truly unresolved.
  // AddressModelBackend::evaluateFixup resolved the value and the bytes are
  // already back-filled. Target backends that force relocations (ARM BL/BLX,
  // AArch64 ADRP, specifiers with @PLT/@GOT) still route through here.
  // In B2 mode these are already handled — suppress unconditionally.
  // Any truly unresolvable symbol would have made evaluateFixup return
  // nullopt, which prevents applyFixup from running at all.
  (void)F;
  (void)Fixup;
  (void)Target;
  (void)FixedValue;
}

uint64_t FinalImageObjectWriter::writeObject() {
  uint64_t TotalBytes = 0;

  // Helper: append ISA-correct NOP padding for text sections via the backend's
  // writeNopData(). Falls back to zero-fill if writeNopData() fails.
  auto appendNopPad = [&](std::vector<uint8_t> &Buf, uint64_t PadSize,
                          const MCSubtargetInfo *STI) {
    SmallVector<char, 64> NopBuf;
    raw_svector_ostream NopOS(NopBuf);
    if (Asm->getBackend().writeNopData(NopOS, PadSize, STI)) {
      Buf.insert(Buf.end(), reinterpret_cast<const uint8_t *>(NopBuf.data()),
                 reinterpret_cast<const uint8_t *>(NopBuf.data()) +
                     NopBuf.size());
    } else {
      Buf.resize(Buf.size() + PadSize, 0x00);
    }
  };

  for (MCSection &Sec : *Asm) {
    StringRef Name = Sec.getName();
    uint64_t SecVA =
        Opts.Model.getSectionVA ? Opts.Model.getSectionVA(Name) : 0;

    mc_rewrite::RewriteSection RS;
    RS.Name = Name.str();
    RS.VA = SecVA;

    uint64_t Size = Asm->getSectionAddressSize(Sec);
    bool IsText = Name.contains("text") || Name.contains("TEXT");
    RS.Bytes.reserve(Size);

    // Grab a subtarget pointer from the first fragment (for writeNopData).
    const MCSubtargetInfo *SecSTI = nullptr;
    for (const MCFragment &F : Sec) {
      if (F.getSubtargetInfo()) {
        SecSTI = F.getSubtargetInfo();
        break;
      }
    }

    for (const MCFragment &F : Sec) {
      uint64_t FOffset = Asm->getFragmentOffset(F);

      // Fill gap between the current output position and the fragment's offset
      // with ISA-correct NOPs (text) or zeros (data).
      if (RS.Bytes.size() < FOffset) {
        uint64_t Gap = FOffset - RS.Bytes.size();
        if (IsText)
          appendNopPad(RS.Bytes, Gap, SecSTI);
        else
          RS.Bytes.resize(FOffset, 0x00);
      }

      auto Content = F.getContents();
      RS.Bytes.insert(RS.Bytes.end(),
                      reinterpret_cast<const uint8_t *>(Content.data()),
                      reinterpret_cast<const uint8_t *>(Content.data()) +
                          Content.size());
      auto Var = F.getVarContents();
      if (!Var.empty())
        RS.Bytes.insert(RS.Bytes.end(),
                        reinterpret_cast<const uint8_t *>(Var.data()),
                        reinterpret_cast<const uint8_t *>(Var.data()) +
                            Var.size());

      // Alignment fragments (FT_Align, FT_PrefAlign) have padding that's
      // generated by writeNopData() during standard emission, not stored in
      // getContents()/getVarContents(). Generate the padding here.
      uint64_t FragSize = Asm->computeFragmentSize(F);
      uint64_t Written = Content.size() + Var.size();
      if (FragSize > Written) {
        uint64_t PadSize = FragSize - Written;
        if (IsText && (F.getKind() == MCFragment::FT_Align ||
                       F.getKind() == MCFragment::FT_PrefAlign)) {
          appendNopPad(RS.Bytes, PadSize,
                       F.getSubtargetInfo() ? F.getSubtargetInfo() : SecSTI);
        } else if (IsText) {
          appendNopPad(RS.Bytes, PadSize, SecSTI);
        } else {
          RS.Bytes.resize(RS.Bytes.size() + PadSize, 0x00);
        }
      }
    }

    // Pad to the section's full address size.
    if (RS.Bytes.size() < Size) {
      uint64_t Remaining = Size - RS.Bytes.size();
      if (IsText)
        appendNopPad(RS.Bytes, Remaining, SecSTI);
      else
        RS.Bytes.resize(Size, 0x00);
    }

    TotalBytes += RS.Bytes.size();
    Out.Sections.push_back(std::move(RS));
  }

  // Collect defined symbols. Some targets (ARM32 ELF) leave symbols in the
  // table whose MCSymbol pointers reference freed or invalid memory after
  // layout; guard every dereference with address-range plausibility checks.
  if (Asm) {
    for (const MCSymbol &Sym : Asm->symbols()) {
      // Skip symbols that may crash on property access.
      if (Sym.isVariable() || Sym.isTemporary())
        continue;
      bool InSec = Sym.isInSection();
      bool IsAbs = !InSec && Sym.isAbsolute();
      if (!InSec && !IsAbs)
        continue;
      uint64_t VA = 0;
      if (InSec) {
        StringRef SecName = Sym.getSection().getName();
        uint64_t SecVA =
            Opts.Model.getSectionVA ? Opts.Model.getSectionVA(SecName) : 0;
        VA = SecVA + Asm->getSymbolOffset(Sym);
      } else {
        VA = Asm->getSymbolOffset(Sym);
      }
      Out.SymbolAddrs[Sym.getName().str()] = VA;
    }
  }

  if (Opts.onImage)
    Opts.onImage(Out.Sections);

  return TotalBytes;
}

std::unique_ptr<MCObjectWriter>
llvm::mc_rewrite::createFinalImageObjectWriter(
    const mc_rewrite::RewriteOptions &Opts,
    mc_rewrite::RewriteResult &Result) {
  return std::make_unique<FinalImageObjectWriter>(Opts, Result);
}
