; Test PtrToInt instruction instrumentation support in the Instrumentor pass.
; This test verifies that ptrtoint instructions are properly instrumented with
; both pre and post callbacks, including support for different integer sizes,
; result replacement, and multiple pointer-to-integer conversions.
;
; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instrumentor -instrumentor-read-config-files=%S/ptrtoint_config.json -S | FileCheck %s


define noundef i64 @test_ptrtoint_basic(ptr noundef %ptr) {
; CHECK-LABEL: define noundef i64 @test_ptrtoint_basic(
; CHECK-SAME: ptr noundef [[PTR:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @__instrumentor_pre_ptrtoint(ptr [[PTR]]) #[[ATTR0:[0-9]+]]
; CHECK-NEXT:    [[ADDR:%.*]] = ptrtoint ptr [[PTR]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @__instrumentor_post_ptrtoint(ptr [[PTR]], i64 [[ADDR]]) #[[ATTR0]]
; CHECK-NEXT:    ret i64 [[TMP0]]
;
entry:
  %addr = ptrtoint ptr %ptr to i64
  ret i64 %addr
}


define noundef i32 @test_ptrtoint_i32(ptr noundef %ptr) {
; CHECK-LABEL: define noundef i32 @test_ptrtoint_i32(
; CHECK-SAME: ptr noundef [[PTR:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @__instrumentor_pre_ptrtoint(ptr [[PTR]]) #[[ATTR0]]
; CHECK-NEXT:    [[ADDR:%.*]] = ptrtoint ptr [[PTR]] to i32
; CHECK-NEXT:    [[TMP0:%.*]] = zext i32 [[ADDR]] to i64
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @__instrumentor_post_ptrtoint(ptr [[PTR]], i64 [[TMP0]]) #[[ATTR0]]
; CHECK-NEXT:    [[TMP2:%.*]] = trunc i64 [[TMP1]] to i32
; CHECK-NEXT:    ret i32 [[TMP2]]
;
entry:
  %addr = ptrtoint ptr %ptr to i32
  ret i32 %addr
}


define void @test_ptrtoint_multiple(ptr noundef %p1, ptr noundef %p2) {
; CHECK-LABEL: define void @test_ptrtoint_multiple(
; CHECK-SAME: ptr noundef [[P1:%.*]], ptr noundef [[P2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @__instrumentor_pre_ptrtoint(ptr [[P1]]) #[[ATTR0]]
; CHECK-NEXT:    [[A1:%.*]] = ptrtoint ptr [[P1]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @__instrumentor_post_ptrtoint(ptr [[P1]], i64 [[A1]]) #[[ATTR0]]
; CHECK-NEXT:    call void @__instrumentor_pre_ptrtoint(ptr [[P2]]) #[[ATTR0]]
; CHECK-NEXT:    [[A2:%.*]] = ptrtoint ptr [[P2]] to i64
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @__instrumentor_post_ptrtoint(ptr [[P2]], i64 [[A2]]) #[[ATTR0]]
; CHECK-NEXT:    [[DIFF:%.*]] = sub i64 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    call void @use_value(i64 [[DIFF]])
; CHECK-NEXT:    ret void
;
entry:
  %a1 = ptrtoint ptr %p1 to i64
  %a2 = ptrtoint ptr %p2 to i64
  %diff = sub i64 %a1, %a2
  call void @use_value(i64 %diff)
  ret void
}


define noundef i64 @test_ptrtoint_gep(ptr noundef %base, i64 %offset) {
; CHECK-LABEL: define noundef i64 @test_ptrtoint_gep(
; CHECK-SAME: ptr noundef [[BASE:%.*]], i64 [[OFFSET:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[PTR:%.*]] = getelementptr inbounds i8, ptr [[BASE]], i64 [[OFFSET]]
; CHECK-NEXT:    call void @__instrumentor_pre_ptrtoint(ptr [[PTR]]) #[[ATTR0]]
; CHECK-NEXT:    [[ADDR:%.*]] = ptrtoint ptr [[PTR]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @__instrumentor_post_ptrtoint(ptr [[PTR]], i64 [[ADDR]]) #[[ATTR0]]
; CHECK-NEXT:    ret i64 [[TMP0]]
;
entry:
  %ptr = getelementptr inbounds i8, ptr %base, i64 %offset
  %addr = ptrtoint ptr %ptr to i64
  ret i64 %addr
}


declare void @use_value(i64)
